Added FAQ Page Implementation for Improved User Support
Mehtarishita/StationGuide pull request #477
Opened 2024-10-31 11:04 UTC by SrijaVuppala295

# Pull Request Template for GSoC 2024

## Related Issue

[Please list any related issue numbers that this pull request resolves. If none, state "None"]

closes:#287

## Description of Changes

This pull request introduces a new FAQ (Frequently Asked Questions) page aimed at enhancing user support and providing quick answers to common inquiries. The following changes have been made:

- FAQ Component: Created a responsive FAQ component using React, which allows users to expand or collapse questions to view answers.
- Dynamic Content: Integrated a data structure to manage FAQ items dynamically, making it easier to update or add new questions and answers in the future.
- User-Friendly Design: Implemented a clean and intuitive design for the FAQ page, enhancing usability with visual cues such as icons and animations for expanded/collapsed states.
- Navigation Integration: Included navigation functionality to allow users to return to the home page easily, improving overall user experience.
- Styling Updates: Applied CSS styles to ensure that the FAQ page is visually consistent with the rest of the application, including adjustments for mobile responsiveness.
- This FAQ page aims to reduce the volume of support inquiries by providing users with immediate access to commonly sought information, thereby improving user satisfaction and engagement.

## Type of Pull Request

- [ ] Bug Fix
- [x] New Feature
- [ ] Performance Improvement
- [x] Documentation Update
- [x] Code Refactoring
- [ ] Security Enhancement
- [ ] Other (Specify): _______________

(Please check relevant boxes by entering an "X" inside them)

## Screenshots / Demo (if applicable)

![image](https://github.com/user-attachments/assets/3110b71b-cd36-4cfa-9a82-1efcb0fb40e8)

![image](https://github.com/user-attachments/assets/1fb9cdbe-1b47-4dc6-aa33-ba6451bec37d)

## Checklist for Contributor
use'X' in [ ] to check it .

- [x] I have reviewed my code before submission.
- [x] I have read and followed the project's Contribution Guidelines.
- [x] I have tested the code thoroughly.
- [x] I have attached related issue numbers, screenshots, or videos (if applicable).
- [x] I have added comments to my code where necessary for clarity.
- [x] I have checked the existing code base and my changes do not introduce any breaking changes.
- [x] My PR addresses only one issue; I have created separate PRs for other issues.
- [x] I have ensured that the PR does not include unrelated files.
- [x] I am mindful of the project's coding standards and best practices.

## Additional Information

[Include any additional context or relevant information that may help in reviewing this PR.]

## Contribution Guidelines Reminder

Thank you for contributing to our project! Please ensure you follow the guidelines below:

### Contribution Levels

2. **Task Categories:**
   - **Basic Tasks:** Primarily focused on small changes like minor bug fixes, documentation improvements, and unit testing. Labeled as **Easy**.
   - **Intermediate Tasks:** Moderate-level tasks that involve enhancing existing features, code refactoring, or performance improvements. Labeled as **Medium**.
   - **Advanced Tasks:** Complex tasks like building new features, significant refactoring, or critical bug fixes. Labeled as **Hard**.

3. **Acknowledging Effort:**
   - Exceptional contributions will be recognized with a higher contribution level if substantial effort and innovation are demonstrated.

### Review Process

- PRs will be reviewed by the maintainers, and feedback will be provided. Contributors should address feedback promptly and resubmit the PR if necessary.

- Contributors are encouraged to participate in the review process of other PRs for community growth.

We appreciate your time and effort in improving this project and look forward to your valuable contributions!

2024-10-31 11:06 UTC, SrijaVuppala295 commented
@dhairyagothi , please add level 3 label , I have created all the content acc to the UI !!!

2024-10-31 16:43 UTC, dhairyagothi commented
![image](https://github.com/user-attachments/assets/a8c364db-ba75-49ff-9d3b-079cd5d5d4cc)
@SrijaVuppala295 fix this deployment error

2024-11-01 15:03 UTC, SrijaVuppala295 commented
@dhairyagothi , I have fixed it !! Please review and merge it and please add level 3 label !!

2024-11-02 03:19 UTC, dhairyagothi commented
please resolve conflicting files @SrijaVuppala295

2024-11-02 18:33 UTC, SrijaVuppala295 commented
@dhairyagothi , i  have resolved it , please review it

2024-11-05 04:03 UTC, dhairyagothi approved these changes

2024-11-05 04:05 UTC, dhairyagothi requested changes

2024-11-05 04:05 UTC, dhairyagothi commented on frontend/src/Pages/hamburger.jsx
> +
fix the dom link and css it is not opening and overlapping 

![image](https://github.com/user-attachments/assets/96dfa357-6c6e-436f-8d85-d1afd714da31)

2024-11-05 13:18 UTC, SrijaVuppala295 commented
## @dhairyagothi , I have made the changes ,  created a scrollable hamburger menu , created a new PR ==> #505
![image](https://github.com/user-attachments/assets/f4a13d85-22e1-4c3e-95af-882d089c24da)

2024-11-06 15:54 UTC, closed without merging